AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  IngressIP:
    Type: String
    Description: IP address for inbound access.
    Default: 0.0.0.0
  AllowSSH:
    Type: String
    Description: Allow SSH access from IngressIP.
    AllowedValues: [true, false]
    Default: false
  InstanceType:
    Type: String
    Description: The instance type for the EC2 instance.
    AllowedValues: [t2.micro, t2.small, t2.medium]
    Default: t2.micro
  KeypairName:
    Type: String
    Description: The name of the EC2 key pair to associate with the instance.
    Default: RTMPKeypair
  AMI:
    Type: String
    Description: The AMI to use for the instance.
    Default: ami-058bd2d568351da34
  ProjectName:
    Type: String
    Description: The project name for cost allocation.
    Default: RTMP-Server
  Environment:
    Type: String
    Description: The environment for cost allocation.
    Default: Development

Conditions:
  ShouldAllowSSH:
    !Equals [true, !Ref AllowSSH]

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeypairName
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update and install Nginx
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo apt-get install -y libnginx-mod-rtmp

          # Display Nginx version
          sudo nginx -v

          # Create rtmp configuration file
          echo 'load_module modules/ngx_rtmp_module.so;
            worker_processes  1;
            events {
              worker_connections  8192;
            }

            rtmp {
              server {
                listen 1935;
                chunk_size 4096;
                allow publish 127.0.0.1;
                allow publish ${IngressIP};
                deny publish all;

                application live {
                        live on;
                        record off;
                }
              }
            }' | sudo tee /etc/nginx/nginx.conf

          # Reload Nginx to apply changes
          sudo nginx -s reload

          # Display status after setup
          sudo systemctl status nginx.service
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for the RTMP server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1935
          ToPort: 1935
          CidrIp: !Sub '${IngressIP}/32'
        - !If
          - ShouldAllowSSH
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Sub '${IngressIP}/32'
          - !Ref "AWS::NoValue"
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  ElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  IPAssociation:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref ElasticIP

Outputs:
  TestURL:
    Description: The URL to test the RTMP server.
    Value: !Sub 'rtmp://${ElasticIP}/live/test-key'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-RTMP-URL'